version: "2.2"
services:
  app:
    image: "chat-app"
    container_name: "chat-app"
    restart: unless-stopped
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development

  redis:
    image: "redis:alpine"
    container_name: "redis_server"
    tty: true
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: redis_server

